### ISSUE TITLE
Unsupported numbers

### ISSUE THREAD

**Issue by yawboakye** [niisign/intro_to_programming#3]
@niisign Even though you make [provision](https://github.com/niisign/intro_to_programming/blob/ece459dcb0aae00cbe9b598329366c88774b9a14/092716/fiw.rb#L34) for numbers greater than or equal to a billion, they're not supported in code. I was unable to convert numbers above 9_999_999 to words. At best, you can support the numbers, or remove from code any clues as they're misleading.

**Comment by yawboakye** [comment]
Entering any number in the range `21000..99999` throws an exception like this:

``` shell
Please enter number
99999
./fiw.rb:67:in `fiw': undefined method `+' for nil:NilClass (NoMethodError)
    from ./fiw.rb:89:in `<main>'
```
